name: stepper_list_view
description: StepperListView is an widget that building the list ui with stepper widget.
version: 0.0.1
homepage: https://github.com/subhashDev11/stepper_list_view

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
